### ISSUE TITLE
Why not use a css preprocesser?

### ISSUE THREAD

**Issue by aprilorange** [eatonphil/flighty#1]
However it's not as large as bootstrap, I think a css preprocessor like Stylus would help, maybe you have had a plan for this?

Btw. good job for making the simple and clean framework.🍺

**Comment by eatonphil** [comment]
Yes, you are absolutely right. It is definitely on my to-do list. I didn't realize how necessary it would be until I got into the thick of it. Most of my time has been split working on Thinkful. But I do want to get this taken care of as well. Thanks!
